# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.lsantamaria.currencies"
version = "latest"
name = "Currencies RX buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"

[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"
