# Buildpacks to include in builder
[[buildpacks]]
id = "com.lsantamaria.currencies"
version = "0.0.1"
uri = "../buildpacks/currencies"


# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
run-image = "cnbs/sample-stack-run:alpine"
build-image = "cnbs/sample-stack-build:alpine"
