# Buildpacks to include in builder
[[buildpacks]]
id = "io.buildbacks.samples"
version = "latest"
image= "cnbs/samples"
#uri = "../buildpacks/kotlin-gradle"

[[buildpacks]]
id = "com.lsantamaria.currencies"
version = "0.0.1"
uri = "../buildpacks/currencies"

[[order]]
[[order.group]]
id = "cnbs/samples"
version = "0.0.1"

[[order]]
[[order.group]]
id = "com.lsantamaria.currencies"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
run-image = "cnbs/sample-stack-run:alpine"
build-image = "cnbs/sample-stack-build:alpine"
